name: Deploy to Yandex Object Storage

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload static assets (immutable)
        run: |
          aws s3 sync ./dist "s3://xn--80avakjqg.xn--p1ai/"             --endpoint-url "https://storage.yandexcloud.net"             --exclude "*.html"             --cache-control "public, max-age=31536000, immutable"             --acl public-read             --delete

      - name: Upload HTML (no-cache)
        run: |
          aws s3 sync ./dist "s3://xn--80avakjqg.xn--p1ai/"             --endpoint-url "https://storage.yandexcloud.net"             --exclude "*" --include "*.html"             --cache-control "no-cache, no-store, must-revalidate"             --acl public-read