name: Deploy to Yandex Object Storage

on:
  push:
    branches:
      - main  # или другая ветка для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync files to Yandex Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: xn--80avakjgg.xn--p1ai   # имя твоего бакета (punycode)
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ru-central1
          SOURCE_DIR: ./dist   # папка с собранным сайтом (или ./ если в корне)
          ENDPOINT_URL: https://storage.yandexcloud.net