name: Deploy to Yandex Object Storage

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ru-central1
      AWS_EC2_METADATA_DISABLED: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci && npm run build

      - name: Upload static assets
        run: |
          aws s3 sync ./dist "s3://xn--80avakjqg.xn--p1ai/"             --endpoint-url "https://storage.yandexcloud.net"             --exclude "*.html"             --cache-control "public, max-age=31536000, immutable"             --acl public-read             --delete

      - name: Upload HTML
        run: |
          aws s3 sync ./dist "s3://xn--80avakjqg.xn--p1ai/"             --endpoint-url "https://storage.yandexcloud.net"             --exclude "*" --include "*.html"             --cache-control "no-cache, no-store, must-revalidate"             --acl public-read